<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace Application\AtlasOrm\DataSource\Text;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class TextTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'texts';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'id',
            'title',
            'text',
            'submitter_id',
            'created',
            'updated',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'id' => (object) array (
  'name' => 'id',
  'type' => 'int',
  'size' => 11,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => true,
  'primary' => true,
),
            'title' => (object) array (
  'name' => 'title',
  'type' => 'varchar',
  'size' => 255,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
),
            'text' => (object) array (
  'name' => 'text',
  'type' => 'text',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
),
            'submitter_id' => (object) array (
  'name' => 'submitter_id',
  'type' => 'int',
  'size' => 11,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
),
            'created' => (object) array (
  'name' => 'created',
  'type' => 'datetime',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => true,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
),
            'updated' => (object) array (
  'name' => 'updated',
  'type' => 'datetime',
  'size' => NULL,
  'scale' => NULL,
  'notnull' => false,
  'default' => NULL,
  'autoinc' => false,
  'primary' => false,
),
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'id' => null,
            'title' => null,
            'text' => null,
            'submitter_id' => null,
            'created' => null,
            'updated' => null,
        ];
    }
}
