<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace Application\AtlasOrm\DataSource\User;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class UserTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'users';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'id',
            'email',
            'password',
            'first_name',
            'last_name',
            'created',
            'updated',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'id' => (object) [
                'name' => 'id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => true,
                'primary' => true,
            ],
            'email' => (object) [
                'name' => 'email',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'password' => (object) [
                'name' => 'password',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'first_name' => (object) [
                'name' => 'first_name',
                'type' => 'varchar',
                'size' => 30,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'last_name' => (object) [
                'name' => 'last_name',
                'type' => 'varchar',
                'size' => 30,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'created' => (object) [
                'name' => 'created',
                'type' => 'datetime',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'updated' => (object) [
                'name' => 'updated',
                'type' => 'datetime',
                'size' => null,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'id' => null,
            'email' => null,
            'password' => null,
            'first_name' => null,
            'last_name' => null,
            'created' => null,
            'updated' => null,
        ];
    }
}
